# Generated by Django 4.0.2 on 2022-03-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_items'),
        ('car_trader_app', '0006_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='cart',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
    ]
