# Generated by Django 4.0.2 on 2022-03-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_user'),
        ('car_trader_app', '0007_car_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='cart',
            field=models.ManyToManyField(related_name='cars', to='cart.Cart'),
        ),
    ]
