# Generated by Django 4.0.2 on 2022-03-15 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_trader_app', '0012_remove_car_cart'),
        ('cart', '0006_alter_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', through='cart.CartItem', to='car_trader_app.Car'),
        ),
    ]
