# Generated by Django 4.0.2 on 2022-03-15 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_trader_app', '0012_remove_car_cart'),
        ('cart', '0007_alter_cart_items'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'car')},
        ),
    ]
