# Generated by Django 3.2.12 on 2022-03-04 14:19

import car_trader_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_trader_app', '0005_alter_car_type_alter_review_car_alter_review_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.jpg', upload_to=car_trader_app.models.upload_to)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car_trader_app.car')),
            ],
        ),
    ]
