# Generated by Django 4.0.2 on 2022-03-07 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_trader_app', '0006_images'),
        ('car_trader_app', '0010_alter_car_cart'),
    ]

    operations = [
    ]
