# Generated by Django 4.0.2 on 2022-03-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_trader_app', '0012_remove_car_cart'),
        ('cart', '0005_cart_items_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='cart.CartItem', to='car_trader_app.Car'),
        ),
    ]
